------------------
--这里定义一些常量
------------------

--购买技能的金钱
DefenseAbilitiesGold 	= 200;
AttackAbilitiesGold		= 200;
AuraAbilitiesGold		= 1000;
HealAbilitiesGold		= 200;
SupportAbilitiesGold	= 200;

--复活金钱
RespawnHeroGold = 250

--难度
DifficultyEasy			= 1;
DifficultyNormal		= 2;
DifficultyHard			= 3;
DifficultyCrazy			= 4;
DifficultyHell			= 5;
DifficultyCurrent 		= DifficultyEasy-1;

--升级技能
LEVELUP_ABILITY_BASE_XP_1	= 10;
LEVELUP_ABILITY_BASE_XP_2	= 20;
LEVELUP_ABILITY_BASE_XP_3	= 30;
LEVELUP_ABILITY_BASE_XP_4	= 40;
LEVELUP_ABILITY_BASE_XP_5	= 50;
LEVELUP_ABILITY_BASE_XP_6	= 60;
LEVELUP_ABILITY_BASE_XP_7	= 70;
LEVELUP_AURA_BASE_XP 		= 50;

LEVELUP_ABILITY_BASE_GOLD_1	= 100;
LEVELUP_ABILITY_BASE_GOLD_2	= 200;
LEVELUP_ABILITY_BASE_GOLD_3	= 300;
LEVELUP_ABILITY_BASE_GOLD_4	= 400;
LEVELUP_ABILITY_BASE_GOLD_5	= 500;
LEVELUP_ABILITY_BASE_GOLD_6	= 600;
LEVELUP_ABILITY_BASE_GOLD_7	= 700;
LEVELUP_AURA_BASE_GOLD 		= 500;

DIFFICULTY_LEVELUP_ABILITY_XP 	= 10;
DIFFICULTY_LEVELUP_ABILITY_GOLD = 100;

LEVELUP_ABILITY_BASE_XP = {
	LEVELUP_ABILITY_BASE_XP_1,
	LEVELUP_ABILITY_BASE_XP_2,
	LEVELUP_ABILITY_BASE_XP_3,
	LEVELUP_ABILITY_BASE_XP_4,
	LEVELUP_ABILITY_BASE_XP_5,
	LEVELUP_ABILITY_BASE_XP_6,
	LEVELUP_ABILITY_BASE_XP_7,
	LEVELUP_AURA_BASE_XP
}

LEVELUP_ABILITY_BASE_GOLD = {
	LEVELUP_ABILITY_BASE_GOLD_1,
	LEVELUP_ABILITY_BASE_GOLD_2,
	LEVELUP_ABILITY_BASE_GOLD_3,
	LEVELUP_ABILITY_BASE_GOLD_4,
	LEVELUP_ABILITY_BASE_GOLD_5,
	LEVELUP_ABILITY_BASE_GOLD_6,
	LEVELUP_ABILITY_BASE_GOLD_7,
	LEVELUP_AURA_BASE_GOLD
}
